---
title: "Classification of Robbery Crimes in Urban Toronto"
author: "By Kaiwen Yang"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

# Background & Literature Reviews
- **Background:**

Understanding the complex interplay of socio-economic, temporal, and spatial factors in shaping crime dynamics within urban environments is essential for developing effective crime prevention strategies and safeguarding community well-being. In the bustling metropolis of Toronto, where crime incidents unfold daily, there is a pressing need to explore the underlying determinants of criminal behavior, particularly in high-risk scenarios such as robbery crimes. As a student residing in Toronto, the urgency to comprehend these dynamics is palpable, driven by a desire to mitigate personal risk and contribute to broader efforts aimed at fostering safer neighborhoods.


- **Literature Review:**

Drawing from insights gleaned from existing literature, our research endeavors to elucidate the multifaceted nature of robbery crimes in Toronto, with a keen focus on the intricate relationship between neighborhood quality, temporal patterns, and spatial factors. Building upon seminal studies conducted in diverse urban contexts, such as the investigation into temperature fluctuations and crime rates in New South Wales, Australia [1], and the analysis of temporal variations in homicide rates during weekends and holidays in the United Kingdom [2], our study seeks to contextualize these findings within the unique socio-cultural landscape of Toronto.


# Research Quesiton
- **Question of Interest:**

Do temporal and spatial patterns, along with the socio-economic conditions of neighborhoods, significantly impact the likelihood of robbery crimes occurring in Toronto across different neighborhoods?

- **Temporal Factors:**

Season, month, day of the week, hour of the day, and the presence of sunset at the time of the crime.

- **Spatial Patterns:**

Longitude, latitude, and premise type of the location of the crime.

- **Socio-Economic Indicators of Neighborhoods:**

Income levels, housing density, number of rental properties, permanent job and labor force ratio, transportation service worker and population ratio, healthcare service worker and population ratio, and the difference in individuals' median and average income, will also be considered.

# Data Source

- **Toronto Open Data Catalogue[3]:**
2021 Toronto Census, could be downloaded directly from website.

- **Toronto Police Service Public Safety Data Portal[4]:**
Seven crimes reports, including Auto Theft, Bicycle Theft, Break and Enter, Homicides, Robbery,  Shooting and Firearm Discharges and Theft Over, could be downloaded directly from website. 

# Statistical Models Used

- **Generalized Linear Model (GLM)**

- **Classification Tree**

- **Bagging**

- **Random Forest**

- **Boosting**

- **XGBoost**

# Summary of Findings

- **Advanced EDA Findings:**

A notable cluster of high robbery counts emerges in neighborhoods characterized by low median income but high permanent job labor force ratios. Moreover, robbery counts surge in darkness across all premises types, with commercial and educational areas showing particularly wide ranges of counts during dark hours, indicating heightened risk. Commercial and outdoor premises consistently exhibit higher robbery counts compared to other types, suggesting specific vulnerabilities in these areas. Temporal trends also unveil distinct patterns, with robbery counts peaking during winter months, coinciding with holiday-related crime rate increases, and surging in summer, aligning with higher temperatures. Additionally, weekends witness elevated robbery counts compared to weekdays, and robbery incidents rise from afternoon to midnight, sharply declining at 2 AM, reflecting dynamic temporal dynamics shaping criminal activity.

- **Statistical Model Findings:**

Random Forest and Bagging models demonstrate superior performance across various metrics, including training and testing accuracy, precision, recall, and F1 score, surpassing other models in predictive efficacy. Particularly, Random Forest achieves higher precision, essential for accurately identifying actual robbery cases and reducing unnecessary panic. Variable importance analysis underscores the significance of spatial indicators such as Longitude, Latitude, and Premises_Type, followed by temporal factors like Hour, Month, Day_of_Week, and Season. Socio-economic factors, including Number_of_Rental_Properties and Permanent_Job_and_Labour_Force_Ratio, also play pivotal roles in the model, with newly created variables showing promise in enhancing prediction accuracy and understanding underlying trends in robbery incidents.

# References

[1] “Hot and bothered? Associations between temperature and crime in Australia”, Heather R. Stevens & Paul J. Beggs & Petra L. Graham & Hsing-Chung. 
Available at: 
https://www.researchgate.net/publication/331499161_Hot_and_bothered_Associations_between_temperature_and_crime_in_Australia 

[2] “Do homicide rates increase during weekends and national holidays?”, Alison Baird, David While, Sandra Flynn, Saied Ibrahim, Navneet Kapur, Louis Appleby & Jenny Shaw. 
Available at: 
https://www.researchgate.net/publication/332279464_Do_homicide_rates_increase_during_weekends_and_national_holidays 

[3] Toronto Open Data Catalogue.
Available at: 
https://open.toronto.ca/dataset/neighbourhood-profiles/

[4] Toronto Police Service Public Safety Data Portal. 
Available at: 
https://data.torontopolice.on.ca/pages/open-data

# Appendix
Source of the analysis available at my github repository:
https://github.com/KaiwenYangUT/Robbery_Crime_Classification
